sudo: false

language: python

python:
- '2.7'
- '3.3'

before_install:
- pip install -U pip setuptools

install:
- pip install .

before_script:
- pip install hacking
- flake8 .

script:
- pip install pytest
- which pytest || which py.test
- pytest -vs .

branches:
  only:
    - master
